[General]

Background="backgrounds/bg.png"
font="Cantarell"
Padding="50"
CornerRadius="5"
GeneralFontSize="9"
LoginScale="0.100"

TextFieldColor="ffffff"
TextFieldTextColor="#000000"
TextFieldBorderColor="#000000"

LoginButtonTextColor="#1e1d2f"
LoginButtonBgColor="#7c7f93"
LoginButtonText="WHAT!"
LoginButtonBorderColor="#000000"

PopupBgColor="#000000"
PopupHighlightColor="#ffffff"

SessionButtonColor="#000000"
SessionIconColor="#ffffff"

PowerButtonColor="#000000"
PowerIconColor="#ffffff"

DateColor="#ffffff"
DateSize="30"
DateIsBold="false"
DateOpacity="0.8"
DateFormat="dddd, MMMM d"

TimeColor="#ffffff"
TimeSize="60"
TimeIsBold="true"
TimeOpacity="0.8"
TimeFormat="hh:mm AP"
